### ISSUE TITLE
MaterialStepper throws IOOBE

### ISSUE THREAD

**Issue by esoco** [GwtMaterialDesign/gwt-material-addins#63] opened 2016-05-02 11:50 UTC
If a stepper is added to it's parent without having children of it's own an IndexOutOfBoundException is thrown. This is caused by the `onLoad()` method calling `goToStep(currentStepIndex + 1)`.  `goToStep` does not validate the index argument, causing the mentioned exception because the (empty) widget list is accessed at a wrong index. In my opinion it should be legitimate to initialize a stepper without content and only fill it later as this is the case with other GWT panels. 

As the addition above indicates the stepper interfaces uses indexes starting at 1 to identify the steps. This is quite uncommon in Java development and I would advise to change that to a zero-based index instead to prevent programming errors (internally as well as externally).

**Comment by kevzlou7979** [comment] 2016-05-09 04:24
Fixed with commit - https://github.com/GwtMaterialDesign/gwt-material-addins/commit/90fcc3cf06e09f5163f0da6d091e80639f3eddc1

For the indexing it was intended to use the default index.

**Closed by kevzlou7979** 2016-05-09 04:24 UTC
Labels: bug

**Comment by esoco** [comment] 2016-05-09 08:21
Thanks for fixing the bug. But what do you mean with "default index"? The typical default in Java are indexes starting at zero.
