### ISSUE TITLE
MaterialAutoComplete addin should have placeholder & label, like MaterialValueBox

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material-addins#270] opened 2017-10-07 13:48 UTC
Currently the placeholder behaves like a label - when the text box contains a value the placeholder is relocated above the text box.
But sometimes you (me! :) don't want that, you want no extra label floating around the text box.

What I believe needs to be done is to add a `label` attribute/field that would do what currently the `placeholder` does. And the `placeholder` would be changed to behave like a proper placeholder, i.e. consistently with MaterialValueBox.

**It is a minor amount of work which I am willing to do if you give it a go.**

As for backwards compatibility, I believe the change would be a non-breaking one, placeholders would simply cease relocating above their text boxes, and you would achieve the old behaviour by simply replacing the `placeholder` attribute with a `label` attribute.

**Comment by BenDol** [comment] 2017-10-07 20:59
what version are you referring to? and what components are you referring to? Checking here: https://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#forms it all behaves as intended.

**Comment by jzaruba** [comment] 2017-10-07 21:02
I am talking about a MaterialAutoComplete **add-in**: https://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#autocomplete

**Comment by BenDol** [comment] 2017-10-07 21:05
Okay Pull Requests are welcome if you would like to submit this patch on the `release_2.0` branch. As for backwards compatibility, we could back port it after the PR is accepted.

**Comment by kevzlou7979** [comment] 2017-10-17 07:45
Thanks @jzaruba , fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/pull/275

**Closed by kevzlou7979** 2017-10-17 07:45 UTC
Labels: ready
